# # GitHub CI build pipeline
# name: Awesome Calculator CI build

# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:
#     branches:
#       - master
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up python 3.7
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7
#     - name: Install dependencies
#       run: |
#         cd src
#         python -m pip install --upgrade pip
#         pip install coverage
#         if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Run Unit Tests and generate coverage report
#       run: |
#         cd src
#         python -m unittest -v
#         coverage run -m unittest
#         coverage report
#         coverage html
#     - name: Archive code coverage html report
#       uses: actions/upload-artifact@v2
#       with:
#         name: code-coverage-report
#         path: src/htmlcov
#     - name: Run package creation
#       run: |
#         cd src
#         python -m pip install --user --upgrade build
#         python -m build
#     - name: Archive package
#       uses: actions/upload-artifact@v2
#       with:
#         name: awesome-calculator
#         path: src/dist    

name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests and generate coverage report
        run: |
          cd src
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: src/htmlcov/

      - name: Run package creation
        run: |
          cd src
          python -m build

      - name: Debug - List dist directory contents
        run: |
          echo "Listing contents of src/dist directory:"
          ls -la src/dist/

      - name: Verify .whl file exists
        run: |
          WHEEL_FILE=$(find src/dist -name "*.whl")
          if [ -z "$WHEEL_FILE" ]; then
            echo "No wheel file found!"
            exit 1
          else
            echo "Wheel file found: $WHEEL_FILE"
          fi

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: awesome-calculator
          path: src/dist/*

  install-package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: awesome-calculator

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          WHEEL_FILE=$(find . -name "*.whl")
          if [ -z "$WHEEL_FILE" ]; then
            echo "No wheel file found to install!"
            exit 1
          else
            echo "Installing wheel file: $WHEEL_FILE"
            pip install "$WHEEL_FILE"
          fi
